// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        int64                 `json:"id"`
	UserID    sql.NullInt64         `json:"user_id"`
	Action    string                `json:"action"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	IpAddress pqtype.Inet           `json:"ip_address"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Contract struct {
	ID           int64         `json:"id"`
	MarketID     sql.NullInt64 `json:"market_id"`
	ContractType string        `json:"contract_type"`
	PriceCents   int32         `json:"price_cents"`
	Volume       int64         `json:"volume"`
}

type KycVerification struct {
	UserID      int64        `json:"user_id"`
	SsnLast4    string       `json:"ssn_last4"`
	Dob         time.Time    `json:"dob"`
	Address     string       `json:"address"`
	KycStatus   bool         `json:"kyc_status"`
	SubmittedAt time.Time    `json:"submitted_at"`
	VerifiedAt  sql.NullTime `json:"verified_at"`
}

type Market struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	ClosesAt    time.Time `json:"closes_at"`
	ResolvesAt  time.Time `json:"resolves_at"`
}

type MarketResolution struct {
	MarketID   int64     `json:"market_id"`
	Outcome    string    `json:"outcome"`
	ResolvedBy int64     `json:"resolved_by"`
	ResolvedAt time.Time `json:"resolved_at"`
}

type Order struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	ContractID int64        `json:"contract_id"`
	OrderType  string       `json:"order_type"`
	OrderStyle string       `json:"order_style"`
	PriceCents int32        `json:"price_cents"`
	Quantity   int32        `json:"quantity"`
	Status     string       `json:"status"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Trade struct {
	ID          int64     `json:"id"`
	BuyOrderID  int64     `json:"buy_order_id"`
	SellOrderID int64     `json:"sell_order_id"`
	ContractID  int64     `json:"contract_id"`
	PriceCents  int32     `json:"price_cents"`
	Quantity    int32     `json:"quantity"`
	ExecutedAt  time.Time `json:"executed_at"`
}

type Transaction struct {
	ID           int64         `json:"id"`
	UserID       int64         `json:"user_id"`
	Type         string        `json:"type"`
	AmountCents  int64         `json:"amount_cents"`
	BalanceAfter int64         `json:"balance_after"`
	CreatedAt    time.Time     `json:"created_at"`
	ReferenceID  uuid.NullUUID `json:"reference_id"`
}

type User struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Username     string       `json:"username"`
	CreatedAt    sql.NullTime `json:"created_at"`
	IsVerified   bool         `json:"is_verified"`
}

type Wallet struct {
	UserID       int64        `json:"user_id"`
	BalanceCents int64        `json:"balance_cents"`
	LockedCents  int64        `json:"locked_cents"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
