// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        int64                 `json:"id"`
	UserID    sql.NullInt64         `json:"user_id"`
	Action    string                `json:"action"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	IpAddress pqtype.Inet           `json:"ip_address"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Contract struct {
	ID           int64          `json:"id"`
	MarketID     sql.NullInt64  `json:"market_id"`
	ContractType sql.NullString `json:"contract_type"`
	PriceCents   sql.NullInt32  `json:"price_cents"`
	Volume       sql.NullInt64  `json:"volume"`
}

type KycVerification struct {
	UserID      int64        `json:"user_id"`
	SsnLast4    string       `json:"ssn_last4"`
	Dob         time.Time    `json:"dob"`
	Address     string       `json:"address"`
	KycStatus   bool         `json:"kyc_status"`
	SubmittedAt time.Time    `json:"submitted_at"`
	VerifiedAt  sql.NullTime `json:"verified_at"`
}

type Market struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	Status      sql.NullString `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	ClosesAt    sql.NullTime   `json:"closes_at"`
	ResolvesAt  sql.NullTime   `json:"resolves_at"`
}

type MarketResolution struct {
	MarketID   int64          `json:"market_id"`
	Outcome    sql.NullString `json:"outcome"`
	ResolvedBy sql.NullInt64  `json:"resolved_by"`
	ResolvedAt sql.NullTime   `json:"resolved_at"`
}

type Order struct {
	ID         int64          `json:"id"`
	UserID     sql.NullInt64  `json:"user_id"`
	ContractID sql.NullInt64  `json:"contract_id"`
	OrderType  sql.NullString `json:"order_type"`
	OrderStyle sql.NullString `json:"order_style"`
	PriceCents sql.NullInt32  `json:"price_cents"`
	Quantity   sql.NullInt32  `json:"quantity"`
	Status     sql.NullString `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Trade struct {
	ID          int64         `json:"id"`
	BuyOrderID  sql.NullInt64 `json:"buy_order_id"`
	SellOrderID sql.NullInt64 `json:"sell_order_id"`
	ContractID  sql.NullInt64 `json:"contract_id"`
	PriceCents  sql.NullInt32 `json:"price_cents"`
	Quantity    sql.NullInt32 `json:"quantity"`
	ExecutedAt  sql.NullTime  `json:"executed_at"`
}

type Transaction struct {
	ID           int64          `json:"id"`
	UserID       sql.NullInt64  `json:"user_id"`
	Type         sql.NullString `json:"type"`
	AmountCents  sql.NullInt64  `json:"amount_cents"`
	BalanceAfter sql.NullInt64  `json:"balance_after"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ReferenceID  uuid.NullUUID  `json:"reference_id"`
}

type User struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Username     string       `json:"username"`
	CreatedAt    sql.NullTime `json:"created_at"`
	IsVerified   bool         `json:"is_verified"`
}

type Wallet struct {
	UserID       int64         `json:"user_id"`
	BalanceCents sql.NullInt64 `json:"balance_cents"`
	LockedCents  sql.NullInt64 `json:"locked_cents"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}
