// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const checkVerification = `-- name: CheckVerification :one
SELECT is_verified
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) CheckVerification(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkVerification, id)
	var is_verified bool
	err := row.Scan(&is_verified)
	return is_verified, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO users (email, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, username, created_at
`

type CreateAccountParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type CreateAccountRow struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Username  string       `json:"username"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Email, arg.Username, arg.PasswordHash)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, created_at, is_verified, password_hash FROM users
WHERE id = $1 LIMIT 1
`

type GetUserRow struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	Username     string       `json:"username"`
	CreatedAt    sql.NullTime `json:"created_at"`
	IsVerified   bool         `json:"is_verified"`
	PasswordHash string       `json:"password_hash"`
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
		&i.IsVerified,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT email, username, created_at, is_verified, password_hash FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	Email        string       `json:"email"`
	Username     string       `json:"username"`
	CreatedAt    sql.NullTime `json:"created_at"`
	IsVerified   bool         `json:"is_verified"`
	PasswordHash string       `json:"password_hash"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.Email,
			&i.Username,
			&i.CreatedAt,
			&i.IsVerified,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifications = `-- name: ListVerifications :many
SELECT is_verified
FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListVerificationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVerifications(ctx context.Context, arg ListVerificationsParams) ([]bool, error) {
	rows, err := q.db.QueryContext(ctx, listVerifications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []bool{}
	for rows.Next() {
		var is_verified bool
		if err := rows.Scan(&is_verified); err != nil {
			return nil, err
		}
		items = append(items, is_verified)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1
WHERE email = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Email        string `json:"email"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.Email)
	return err
}

const updateVerification = `-- name: UpdateVerification :exec
UPDATE users
SET is_verified = $1
WHERE id = $2
`

type UpdateVerificationParams struct {
	IsVerified bool  `json:"is_verified"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateVerification(ctx context.Context, arg UpdateVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateVerification, arg.IsVerified, arg.ID)
	return err
}
